### PR TITLE
MetadataParser: Cache property metadata to avoid duplicate parse of STI metadata

### PR DESCRIPTION
**Pull request by pavelkovar**
Also fixes cache misses at [DbalMapper::getRelationshipMapper](https://github.com/nextras/orm/blob/master/src/Mapper/Dbal/DbalMapper.php#L199) when STI is used.

### CODE REVIEW

**Comment by hrach** [comment]
Thank you for this contribution! Could you please elaborate what exactly this fix, enhance? If I understand it correctly, it a) fix some bug b) do some performance enhancement. Am I right?

**Comment by hrach** [comment]
@pavelkovar Please, could you answer my question? Otherwise I'm ok with changes :)

**Comment by pavelkovar** [comment]
Hi, sorry I overlooked your comment.

I'll try to explain it on example. Let's take entities like:
``` php
/**
 * @property int $id {primary}
 * @property string $type {enum self::TYPE_*}
 * @property User|null $author {m:1 User, oneSided=true}
 */
abstract class AbstractNotification extends Abstract
{
    const TYPE_POST = 1;
    const TYPE_COMMENT = 2;
}

class PostNotification extends AbstractNotification {}
class CommentNotification extends AbstractNotification {}
```
and code snippet:
``` php
$coll = $this->notificationRepository->findAll();
foreach ($coll as $entity) {
  echo "Notification type: " . $entity->type  . ", Author: " . $entity->author->name . "\n"; 
}

// Expected output:
// Notification type: 1, Author: abcd
// Notification type: 1, Author: efgh
// Notification type: 2, Author: xyz
// Notification type: 2, Author: ijkl
```

Now let's see what happens when code snippet is executed.

_Before patch:_
When `$entity->author` is called on first entity, _DbalMapper:: getRelationshipMapper_  method creates cache key from property object ID, tries to find something in cache and if nothing is found then fetch and store data to cache. When `$entity->author` is called on second entity, _DbalMapper:: getRelationshipMapper_  method creates cache key from property object ID and try to find something in cache but nothing is found because each entity has own metadata with unique object IDs, so next query is send. In total, two queries are send to fetch author names.

_After patch:_
When `$entity->author` is called on first entity, _DbalMapper:: getRelationshipMapper_  method creates cache key from property object ID, tries to find something in cache and if nothing is found then fetch and store data to cache. When `$entity->author` is called on second entity, _DbalMapper:: getRelationshipMapper_  method creates cache key from property object ID and try to find something in cache. Data is successfully found because each entity use same property metadata. In total, one query is send to fetch author names.

-----

Back to question. It improves metadata parsing which do some performance enhancement. :-)

**Comment by hrach** [comment]
Thanks a lot, merged as 431f74be83b08a991edf3c63b5edbc5ef6b816d1 - with few naming modifications :)

**Pull request closed without merging**
