### PR TITLE
[Nette] Initialize metadata on DIC startup - v4.0

### PR DESCRIPTION
**Pull request by mabar**
When entity is created before MetadataStorage is instantiated, an exception is thrown. It happens when ORM classes are loaded lazily (e.g. via nette/di accessor). This PR fixes the issue.

### CODE REVIEW

**Comment by hrach** [comment]
Hi, thanks for this contribution. It seems that it is a nice solution to the problem, but I don't think it's a generally applicable solution for everybody as Orm may not be used in the whole nette application. So maybe creating a "configuration" option that would enable this if wanted? Wdyt?

**Comment by mabar** [comment]
> I don't think it's a generally applicable solution

Yeah, it's not. I don't think any better way exists because ORM initialization depends on static class. Each DI integration has to implement this itself.

> creating a "configuration" option that would enable this if wanted

Yeah, I could change it to something like that. Any opinion on how should the option be named?

```neon
nextras.orm:
	preloadMeta: true
```

**Comment by hrach** [comment]
`preloadMetadata` seems good :) (let's not use shortcut)

**Comment by mabar** [comment]
Okay, done. Is it okay that I retargeted to v4.0? Since it is opt-in feature.

**Comment by hrach** [comment]
Please open a separate PR for the other branch.

**Comment by hrach** [comment]
Thank you!

**Pull request merged**
