### PR TITLE
persistance: fixed & improved persisting of cyclic relationships

### PR DESCRIPTION
**Pull request by JanTvrdik**

### CODE REVIEW

**Comment by hrach** [comment]
Are you able to describe what has been changed? Like `The previous implementation didn't visit all nodes`...

**Comment by JanTvrdik** [comment]
Not really, because I don't understand how did the previous implementation work. I actually don't understand some stuff in my currently proposed implementation as well (see the TODOs in code).

I have done another rewrite which I think handles things a bit better. Will post it soon.

**Comment by JanTvrdik** [comment]
Second rewrite posted, now it should be finally correct (no incorrectly detected cycle on my project).

**Comment by hrach** [comment]
Jan, thanks a lot, it looks great! Still, I wonder, if you/we would be able to write some tests. This is the core funcitonality and if we found a bug, we should be able to track it down.

**Comment by hrach** [comment]
Your description of the bug

> tak jsem to přibližně izoloval – pokud máme dvě entity X a Y provázané 1:1 vazbou, kde Y má isMain=true, tak persist(X) selže zatím co persist(Y) projde (udělá lineárně insert X, insert Y)

was correct! 16b0a87cf2e28481c8e2ab4d3c6b22ad84671bf1

**Pull request merged**
