### PR TITLE
Fixed problem with DateTimeImmutable as a primary key

### PR DESCRIPTION
**Pull request by attreid**

### CODE REVIEW

**Comment by hrach** [comment]
Thanks for the contribution! 🎉 

1) The import is wrong, you have changed type from \DateTimeImmutable to the Nextras' impl.
2) I don't see the reason for importing the class, imo is not connected to the bugfix.

**Comment by attreid** [comment]
1. I forget to run tests, I will correct it

2. when i use DateTimeImmutable as primary key application fall on
https://github.com/nextras/orm/blob/master/src/Repository/IdentityMap.php#L64 with error "Object of class DateTimeImmutable could not be converted to string"

**Comment by hrach** [comment]
to the 2) that's imo fixed by the is_array check, isn't it?

**Comment by attreid** [comment]
no it isnt, because is_array fixed retype DateTimeImmutable to array (its looking like 3 keys)

**Comment by attreid** [comment]
now is correct?
DateTimeImmutable from dbal is needed because it have method tostring to fixed this issue
only in first if is base DateTimeImmutable, so now it work properly

**Comment by attreid** [comment]
the other way is add condition if persitentId in abstractEntity contains DateTimeImmutable retype it on string

**Comment by hrach** [comment]
Thanks for the reporting and PR, fixed a little bit differently :)

**Comment by hrach** [comment]
Today morning I've realized I'm idiot and I've fixed it only for composite PK. Which is, probably, a majority of usecases. Not sure if it's ok, @JanTvrdik  what do you think?

**Pull request closed without merging**
