### PR TITLE
bug 1:1 relationship

### PR DESCRIPTION
**Pull request by qwerin**
Nasel jsem chybku viz:

```php 
public function testGetEntity(): void
	{
		$ean = new Ean();
		$ean->code = '1234';
		$ean->book = $this->orm->books->getByIdChecked(1);
		$this->orm->eans->persistAndFlush($ean);
		$eanId = $ean->id;

		$this->orm->clear();

		$ean = $this->orm->eans->getByIdChecked($eanId);
		$book = $ean->book;
		Assert::equal(1, $book->id);

	}

### CODE REVIEW

**Comment by hrach** [comment]
What is the bug? it is intenionally done the way the Ean cannot exist without a booking.

**Comment by qwerin** [comment]
Jo ale o to tolik nejde jako ze nedunguje dotaz EAN -> book

**Comment by hrach** [comment]
Which version? Do you use `main` only?

**Comment by qwerin** [comment]
on **v4** work, on **main** not work is buggy

**Comment by hrach** [comment]
Thank you very much for the report and test case. Fixing in #620.

**Pull request closed without merging**
