### PR TITLE
Custom functions

### PR DESCRIPTION
**Pull request by JanTvrdik**

### CODE REVIEW

**Comment by hrach** [comment]
The problem here is that we want to introduce such custom functions also to the ArrayCollection. However, ArrayCollection may be used also with DbalMapper and therefore such custom array function may be implemented also with it's dbal equivalent. 

1) We may bring such custom array functions to DbalMapper and make the difference in the custom function name. So something like `processFunctionLike` and `processArrayFunctionLike`. 

2) We may move the funcitons to another class/infrastructure; we may introduce new things exactly for this, though I had no idea how it should look like.

I had discussed this briefly with @JanTvrdik but we didn't come up with something nice. Any idea to this? cc @matej21

**Comment by hrach** [comment]
Another may be:

Make standardized interface on the mapper layer andd pass there a ICollection. Then it's user's call if he will assert($c instanceof DballCollection) and get's the query builder by $c->getQueryBuilder or will also implement else method for ArrayCollection.

What do you think? This seems to be a best option for me for now.

**Comment by hrach** [comment]
Ok, I've chosen the two methods way.

But there are another questions:

1) Dbal custom functions has to return array expressions, which allows nested expressions in findBy. Stil, the custom functions receive the Query builder and may modify it. I'd like to allow more robust modification on query builder itself than returning an array. (e.g. inner join filtering). 

This may be achieved by returning a null. Returning a null would require to do your modifications directly on the query builder.

2) Also, it would be prette convenient to allow custom functions also for ordering. Current implementation allows it easily for DbalCollection (aka modify query builder and return null), but does not allow it for for ArrayCollection, where it expects filtering clousure. 

This may be solved by modifying array collection filtering functions to receive the whole collection and do the filtering/ordering by itself, or better, by using some helper methods in ArrayCollectionHelper. Also, the custom functions could be somehow invoked from oderBy() method on ICollection, probably something as passing an array `$collection->orderBy(['custom function name', ...$params])`.

**Comment by JanTvrdik** [comment]
@hrach btw, @matej21 has redesigned version somewhere

**Comment by hrach** [comment]
Would be great if it would be done in public. It is not good when somebody curates & rething things for hours and there is another separate worke done by other.

**Comment by hrach** [comment]
In https://github.com/nextras/orm/commits/custom_functions is WIP implementation.

Todo:
- rename Filtering function to Function, Nested to Filtering
- add ICollection::applyFunction()
- join filtering & ordering callbackes in ArrayCollection to retain callback order after adding applyFunction()
- caching and creating functions in repository
- documentation

**Comment by hrach** [comment]
merged highly modified solution https://github.com/nextras/orm/commit/8bea3f4cf5da754260a9f5806259d50153af1207

**Pull request closed without merging**
