### PR TITLE
Repository: prefer real method on mapper over findBy-magic methods

### PR DESCRIPTION
**Pull request by JanTvrdik**

### CODE REVIEW

**Comment by JanTvrdik** [comment]
Intention was to allow method such as `findByBlackMagic` on mapper with `@method` annotation on repository. Unfortunately, I realized that those methods will not work with `TestMapper`.

**Comment by Zarganwar** [comment]
Hi, how this realy works? I would like to perform test where is mapper method linked via @method annotation in repository should be used but TestMapper screams 
`Nextras\Orm\Exception\MemberAccessException: Call to undefined  method Nextras\Orm\TestHelper\TestMapper::methodInsideMapper()`

TestMapper is configured by Nette extension

`

nextras.orm:

	repositoryFinder: Nextras\Orm\Bridges\NetteDI\TestMapperPhpDocRepositoryFinder
`

**Comment by hrach** [comment]
@Zarganwar If you wanna proxy method from your TestMapper, you have add such proxy callback yourself via [addMethod()](https://github.com/nextras/orm/blob/main/src/TestHelper/TestMapper.php#L23).

Usage can be seen here: https://github.com/nextras/orm/blob/336140091ecc6053ec5161b3f48e2803f13be3ad/tests/db/array-init.php

**Comment by Zarganwar** [comment]
@hrach OK, it is nothing mega-comfortable, but it make sense. Thanks a lot

**Pull request closed without merging**
