### PR TITLE
FetchPairsHelper: index by IEntity->getPersistedId

### PR DESCRIPTION
**Pull request by vitkutny**
if key is IEntity use persistedId instead of __tostring()

### CODE REVIEW

**Comment by hrach** [comment]
I would rather implement __toString in entity. Such conditions in fetchPairs does not seem right.

**Comment by vitkutny** [comment]
I already use __toString for string representation of entity. For product __toString return its name, for page __toString returns title, which is the purpose of __toString method, that string representation is not unique and should not be used for indexing

**Comment by hrach** [comment]
Let's introduce an interface! :-) What do you think? IHasKeyIdentifier? :)

**Comment by hrach** [comment]
I plan to support sth like `->fetchPairs('this->qr->code', 'title');`; so it should solve this usecase.

**Comment by hrach** [comment]
#147

**Pull request closed without merging**
