### PR TITLE
FetchPairs: support traversing

### PR DESCRIPTION
**Pull request by robskr**
Should solve #147. Naming probably needs some tweaks.

### CODE REVIEW

**Comment by hrach** [comment]
Hi, thanks for the contribution! It's great.
My questions/thoughts:
- we have quite similar code in ArrayCollectionHelper, but there are some differences
- you don't handle hasMany relationships - in any way. I'm ok probably with not supporting, we may throw an exception.
- you simply iterate over the result, but in fact some "value" may be and and "object" and not an entity and this method will allow iterate over it. This is something what is handled in ArrayCollectionHelper which check this

What do you think?

**Comment by hrach** [comment]
Ok, I have reworked your solution a little: https://github.com/nextras/orm/pull/313
- array collection helper code is quite different, no need to connect these parts
- has many relationships - throwing exception for now - I'm creating a follow up - #314
- checking also for IEntity now.

**Comment by hrach** [comment]
Thanks for your work!

**Comment by robskr** [comment]
Dammit, I missed your first comment. I am sorry for not finishing the work :(

Thank you for completing the feature.

**Pull request closed without merging**
